import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const outputRoot = new URL("../out/", import.meta.url);

test("exports the v5.1 mentorship homepage and participation guide", async () => {
  await access(new URL("index.html", outputRoot));
  await access(new URL("404.html", outputRoot));
  await access(new URL("_next/", outputRoot));
  await access(new URL("logos/dku-logo.jpg", outputRoot));
  await access(new URL("logos/dku-logo-transparent.png", outputRoot));
  await access(new URL("logos/dia-logo.png", outputRoot));
  await access(new URL("mentors/giampietro-schiavo.png", outputRoot));
  await access(new URL("mentors/dennis-chan.png", outputRoot));
  await access(new URL("mentors/tiago-rito.png", outputRoot));
  await access(new URL("mentors/profiles/giampietro-schiavo-natural.jpg", outputRoot));
  await access(new URL("mentors/profiles/dennis-chan-natural.webp", outputRoot));
  await access(new URL("mentors/profiles/tiago-rito-natural.jpg", outputRoot));
  await access(new URL("downloads/dku-global-mentorship-application-2026.docx", outputRoot));
  await access(new URL("posters/dku-mentorship-2026-poster.png", outputRoot));

  const html = await readFile(new URL("index.html", outputRoot), "utf8");
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(html, /DANKOOK UNIVERSITY/);
  assert.match(html, /DANKOOK INSTITUTE OF AGING/);
  assert.match(html, /湲濡쒕쾶 遺꾩옄쨌?명룷?앸Ъ??誘몃옒?몄옱 ?묒꽦 硫섑넗??);
  assert.match(html, /?멸컙吏덊솚??怨좉툒 遺꾩옄쨌?명룷?앸Ъ?숈쟻 湲곗쟾/);
  assert.match(html, /?멸컙 吏덊솚紐⑤뜽留곴낵 ?ㅽ뿕??以묎컻?곌뎄/);
  assert.match(html, /援?젣?숈닠?몃???);
  assert.match(html, /\/logos\/dku-logo\.jpg/);
  assert.match(html, /\/logos\/dku-logo-transparent\.png/);
  assert.match(html, /\/logos\/dia-logo\.png/);
  assert.match(html, /?좊컻 湲곗?/);
  assert.match(html, /?곌뎄 遺꾩빞 ?곹빀??);
  assert.match(html, /援?젣 ?곌뎄 ??웾/);
  assert.match(html, /?곌뎄 吏꾨줈 怨꾪쉷/);
  assert.match(html, /?좊컻 ?몃? 湲곗?? ?닿퇋???곕Ⅴ硫? ?쒖텧???좎껌???댁슜???곕씪 ?좊컻 ?덉젙/);
  assert.match(html, /href="#selection"/);
  assert.match(html, /mailto:dku\.gm2026@gmail\.com/);
  assert.match(html, /dku\.gm2026@gmail\.com/);
  assert.match(html, /MD PARTICIPATION GUIDE/);
  assert.match(source, /id="participation"/);
  assert.match(source, /1박 최대 10만원/);
  assert.match(html, /?좎껌???묒꽦 ??泥⑤??섏뿬 ?쒖텧/);
  assert.match(html, /硫섑넗留??꾨줈洹몃옩 李몄뿬?좎껌??);
  assert.match(html, /?묒떇 ?ㅼ슫濡쒕뱶/);
  assert.match(html, /\/downloads\/dku-global-mentorship-application-2026\.docx/);
  assert.match(html, /?④뎅?명솕?곌뎄??DIA 쨌 ?섍낵???쨌 ?④뎅??숆탳蹂묒썝 쨌 ?섑븰?듯빀?숆낵/);
  assert.match(html, /蹂닿굔蹂듭?遺 쨌 ?쒓뎅蹂닿굔?곗뾽吏꾪씎??);
  assert.doesNotMatch(html, /珥덈튃 ?덉젙/);
  assert.doesNotMatch(html, /PORTRAIT/);
  assert.doesNotMatch(html, /諛붿씠?ㅼ쑖?⑺븰怨?諛붿씠?ㅼ쑖?⑸???);
  assert.doesNotMatch(html, /href="tel:/);
  assert.doesNotMatch(html, /DANKOOK BIO ATLAS/);
  assert.doesNotMatch(source, /APOE/);
  assert.equal((source.match(/?뱀젙 ?좎쟾??PCR쨌gel image? genotype ?먯젙??g) ?? []).length, 2);
  assert.equal((source.match(/諛곗뼇 湲곕줉怨??명룷 ?덉쭏愿由?泥댄겕由ъ뒪??g) ?? []).length, 2);
  assert.equal((source.match(/SDS-PAGE 諛?band ?뺣웾쨌?댁꽍 寃곌낵/g) ?? []).length, 2);
  assert.match(source, /role="dialog"/);
  assert.match(source, /aria-modal="true"/);
  assert.match(source, /event\.key === "Escape"/);
  assert.match(source, /GLOBAL SCHOLAR 쨌 CORE PROFILE/);
  assert.match(source, /硫섑넗留??꾨줈洹몃옩 李몄뿬?좎껌??br \/>?묒떇 ?ㅼ슫濡쒕뱶/);
  assert.match(html, /D-DAY ?묒닔留덇컧/);
  assert.match(html, /2026??8??21??源뚯?/);
  assert.match(html, /湲濡쒕쾶 ?앺븰 硫섑넗???꾨줈洹몃옩/);
  assert.match(html, /?묒닔 硫붿씪二쇱냼 ?뺤씤/);
  assert.match(html, /dku_gm2026@gmail\.com/);
  assert.match(html, /dku\.gm2026@gmail\.com/);
  assert.match(source, /const \[noticeOpen, setNoticeOpen\] = useState\(true\)/);
  assert.match(source, /aria-labelledby="notice-title"/);
  assert.match(source, /aria-describedby="notice-description"/);
  assert.match(source, /className="notice-confirm"/);
  assert.match(source, /?뺤젙??二쇱냼濡??좎껌 ?쒕쪟瑜??ㅼ떆 ?쒕쾲 諛쒖넚/);
  assert.match(html, /李멸? 怨듦퀬臾?蹂닿린/);
  assert.match(source, /\/posters\/dku-mentorship-2026-poster\.png/);
  assert.match(source, /id="poster-title"/);
  assert.match(source, /aria-label="李멸? 怨듦퀬臾??リ린"/);
});
